name: banana
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
  #- torchvision
  - tensorflow
  - cuda92
  - jupyter
  - notebook
  - matplotlib
  - numpy
  - pandas
  - Pillow
  - tqdm
  - pytest
  - pip:
      - ./unityagents
