name: banana
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - tensorflow
  - cuda92
  - jupyter
  - notebook
  - jupyter_contrib_nbextensions
  - matplotlib
  - numpy
  - pandas
  - Pillow
  - tqdm
  - pytest
  - pip:
      - ./unityagents
